config/routes.rb
Rails.application.routes.draw do
  get 'statics/index'
  devise_for :users, controller: {
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  # Admin namespace
  
  
  authenticated :user, -> user {user.admin?} do
    root to: 'admin/dashboards#index', as: :admin_root_path
  end
  
  authenticated :user do
    root to: 'client/dashboards#index', as: :client_root_path
  end

  # Define the fallback root path for unautenticated
  unauthenticated do
    root to:'statics#index'
  end


  #Admin namespace
  authenticate :user, ->(user) { user.admin?} do
    namespace :admin do

      root "dashboard#index"    #Admin dashboard root
      resources :albums
      resources :songs, param: :id
      resources :artists
    end
  end
    
  #Client namespace
    namespace :client do

      root "dashboard#index"    #Admin dashboard root
      get 'statics/about', to: 'statics#about'
      get 'statics/contact', to: 'statics#contact'
      resources :albums, only: [:index, :show]
      resources :artists, only: [:index, :show]
      resources :statics
      resources :songs, only: [:index, :show]
    end
      
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  get "about" => "statics#about"
  get "contact" => "statics#contact"
end

app/models/client.rb
module Client
  def self.table_name_prefix
    "client_"
  end
end

app/models/client/dashboard.rb
class Client::Dashboard < ApplicationRecord
end

app/models/song.rb
class Song < ApplicationRecord
    has_one_attached :file
    has_one_attached :image

    extend FriendlyId
    friendly_id :title, use: :slugged

    has_many :artist_songs, dependent: :destroy
    has_many :artist, through: :artist_songs

    has_one :album_song, dependent: :destroy
    has_one :album, through: :album_song

    has_many :playlist_songs
    has_many :playlist, through: :playlist_songs
    
end

app/controllers/admin/songs_controller.rb
class Admin::SongsController < ApplicationController
  before_action :set_song, only: %i[ show edit update destroy ]

  # GET /songs or /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1 or /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
    @song.artist_songs.build
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs or /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to song_url(@song), notice: "Song was successfully created." }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1 or /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to song_url(@song), notice: "Song was successfully updated." }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1 or /songs/1.json
  def destroy
    @song.destroy!

    respond_to do |format|
      format.html { redirect_to songs_url, notice: "Song was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def song_params
      params.require(:song).permit(:title, :release, :composer, :file, :image, :producer, artist_ids: [])
    end
end

app/controllers/client/albums_controller.rb
class Client::AlbumsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_album, only: [ :show ]

  # GET /albums or /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1 or /albums/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:title, :about, :release, :image, :credit, song_ids: [])
    end
end

app/controllers/client/artists_controller.rb
class Client::ArtistsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_artist, only: [:show]

  # GET /artists or /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1 or /artists/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def artist_params
      params.require(:artist).permit(:name, :year, :nationality, :biography)
    end
end

app/controllers/client/dashboards_controller.rb
class Client::DashboardsController < ApplicationController
  def index
  end
end

app/controllers/client/playlists_controller.rb
class Client::PlaylistsController < ApplicationController
        def index
          @playlists = Playlist.all
        end
      
        def show
          @playlist = Playlist.find(params[:id])
        end
      
        def new
          @playlist = Playlist.new
        end
      
        def create
          @playlist = Playlist.new(playlist_params)
          if @playlist.save
            redirect_to @playlist
          else
            render :new
          end
        end
      
        private
      
        def playlist_params
          params.require(:playlist).permit(:name, song_ids: [])
        
    end  
end

app/controllers/client/songs_controller.rb
class Client::SongsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_artist, only: [:show]


  # GET /songs or /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1 or /songs/1.json
  def show
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def song_params
      params.require(:song).permit(:title, :release, :composer, :file, :image, :producer, artist_ids: [])
    end
end

app/controllers/client/statics_controller.rb
class Client::StaticsController < ApplicationController
    def index
    end
    def about
    end
    def contact
    end
end

app/helpers/client/dashboards_helper.rb
module Client::DashboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/client/songs/_form.html.erb
<%= form_with(model: song, class: "contents") do |form| %>
  <% if song.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
        <% song.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="field">
  <%= form.label :artist %>
  <%= form.collection_select :artist_ids, Artist.order(:name), :id, :name, {},multiple: true, prompt: "Select the Category", class: "",
  data: { controllerr: 'multi-select',
  target: 'multi-select.select',
  behavior: 'select' } %>
  

  <div class="my-5">
    <%= form.label :release %>
    <%= form.date_field :release, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div>
    <%= form.label :image %><br>
    <%= form.file_field :image %>
  </div>

  <div class="my-5">
    <%= form.label :composer %>
    <%= form.text_field :composer, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :producer %>
    <%= form.text_field :producer, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
  
  <%= form.label :file %><br>
  <%= form.file_field :file %>
  </div>

<% end %>

app/views/client/songs/_song.html.erb
<div id="<%= dom_id song %>">
  <div>
  <% if song.image.attached? %>
  <%= image_tag url_for(song.image), class: "w-10 h-10" %> 
  <% end %>
  </div>

  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= song.title %>
  </p>
  
  <p class="my-5">
    <strong class="block font-medium mb-1">Artist:</strong>
    <% song.artist.each do |artist| %>
      <%= artist.name%>
      <% end %>
  
  <p class="my-5">
    <strong class="block font-medium mb-1">Composer:</strong>
    <%= song.composer %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Producer:</strong>
    <%= song.producer %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Release:</strong>
    <%= song.release %>
  </p>

  <% if @song.file.attached? %>
  <audio controls>
  <source src="<%= url_for(@song.file) %>" type="audio/mpeg">
  your browser does mot support the audio element.
  </audio>
  <% else %>
  <p> no file attached</p>
  <% end %>

</div>

app/views/client/songs/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing song</h1>

  <%= render "form", song: @song %>

  <%= link_to "Show this song", @song, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to songs", songs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/client/songs/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Songs" %>

  <div class="flex justify-between items-center mb-5">
    <h1 class="font-bold text-4xl">Songs</h1>
  </div>

  <table class="min-w-full mt-5">
    <thead>
      <tr>
        <th class="px-4 py-2 bg-cyan-500 text-left">Title</th>
        <th class="px-4 py-2 bg-cyan-500 text-left">Artist</th>
        <th class="px-4 py-2 bg-cyan-500 text-left">Composer</th>
        <th class="px-4 py-2 bg-cyan-500 text-left">Producer</th>
        <th class="px-4 py-2 bg-cyan-500 text-left">Release</th>
      </tr>
    </thead>
    <tbody>
      <% @songs.each do |song| %>
        <tr class="cursor-pointer hover:bg-cyan-500" onclick="window.location='<%= client_song_path(song) %>'">
          <td class="border px-4 py-2"><%= song.title %></td>
          
          <td class="border px-4 py-2"><% song.artist.each do |artist| %>
          <%= artist.name%>
          <% end %>
          </td>
          <td class="border px-4 py-2"><%= song.composer %></td>
          <td class="border px-4 py-2"><%= song.producer %></td>
          <td class="border px-4 py-2"><%= song.release %></td>
           
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/client/songs/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New song</h1>

  <%= render "form", song: @song %>

  <%= link_to "Back to songs", songs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/client/songs/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @song %>
    <%= link_to "Back to songs", client_songs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
  </div>
</div>