config/routes.rb
Rails.application.routes.draw do
  get 'statics/index'
  devise_for :users, controller: {
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  # Admin namespace
  
  
  authenticated :user, -> user {user.admin?} do
    root to: 'admin/dashboards#index', as: :admin_root_path
  end
  
  authenticated :user do
    root to: 'client/dashboards#index', as: :client_root_path
  end

  # Define the fallback root path for unautenticated
  unauthenticated do
    root to:'statics#index'
  end


  #Admin namespace
  authenticate :user, ->(user) { user.admin?} do
    namespace :admin do

      root "dashboard#index"    #Admin dashboard root
      resources :albums
      resources :songs, param: :id
      resources :artists
    end
  end
    
  #Client namespace
    namespace :client do

      root "dashboard#index"    #Admin dashboard root
      get 'statics/about', to: 'statics#about'
      get 'statics/contact', to: 'statics#contact'
      resources :albums, only: [:index, :show]
      resources :artists, only: [:index, :show]
      resources :statics
      resources :songs, only: [:index, :show]
    end
      
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  get "about" => "statics#about"
  get "contact" => "statics#contact"
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    "admin_"
  end
end

app/models/admin/dashboard.rb
class Admin::Dashboard < ApplicationRecord
end

app/models/album.rb
class Album < ApplicationRecord
    has_one_attached :image

    has_many :album_songs, dependent: :destroy
    has_many :songs, through: :album_songs
    
end

app/models/album_song.rb
class AlbumSong < ApplicationRecord
  belongs_to :album
  belongs_to :song
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_rich_text :biography
    
    has_many :artist_songs, dependent: :destroy
    has_many :songs, through: :artist_songs

    validates :name, presence:true
end

app/models/artist_song.rb
class ArtistSong < ApplicationRecord
  belongs_to :artist
  belongs_to :song
end

app/models/client.rb
module Client
  def self.table_name_prefix
    "client_"
  end
end

app/models/client/dashboard.rb
class Client::Dashboard < ApplicationRecord
end

app/models/playlist.rb
class Playlist < ApplicationRecord
    has_many :playlist_songs
    has_many :songs, through: :playlist_songs
end

app/models/playlist_song.rb
class PlaylistSong < ApplicationRecord
  belongs_to :playlist
  belongs_to :song
end

app/models/song.rb
class Song < ApplicationRecord
    has_one_attached :file
    has_one_attached :image

    extend FriendlyId
    friendly_id :title, use: :slugged

    has_many :artist_songs, dependent: :destroy
    has_many :artist, through: :artist_songs

    has_one :album_song, dependent: :destroy
    has_one :album, through: :album_song

    has_many :playlist_songs
    has_many :playlist, through: :playlist_songs
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/artists_controller.rb
class Admin::ArtistsController < ApplicationController
  before_action :set_artist, only: %i[ show edit update destroy ]

  # GET /artists or /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1 or /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists or /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to artist_url(@artist), notice: "Artist was successfully created." }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1 or /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to artist_url(@artist), notice: "Artist was successfully updated." }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1 or /artists/1.json
  def destroy
    @artist.destroy!

    respond_to do |format|
      format.html { redirect_to artists_url, notice: "Artist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def artist_params
      params.require(:artist).permit(:name, :year, :nationality, :biography)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/client/artists_controller.rb
class Client::ArtistsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_artist, only: [:show]

  # GET /artists or /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1 or /artists/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def artist_params
      params.require(:artist).permit(:name, :year, :nationality, :biography)
    end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
    def index
    end
    def about
    end
    def contact
    end
end

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/client/dashboards_helper.rb
module Client::DashboardsHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/admin/artists/_artist.html.erb
<div id="<%= dom_id artist %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= artist.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Year:</strong>
    <%= artist.year %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Nationality:</strong>
    <%= artist.nationality %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Biography:</strong>
    <%= artist.biography %>
  </p>

</div>

app/views/admin/artists/_form.html.erb
<%= form_with(model: artist, class: "contents") do |form| %>
  <% if artist.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
        <% artist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :year %>
    <%= form.date_field :year, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :nationality %>
    <%= form.text_field :nationality, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
  <%= form.label :biography %>
  <%= form.rich_text_area :biography, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/admin/artists/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing artist</h1>

  <%= render "form", artist: @artist %>

  <%= link_to "Show this artist", @artist, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to artists", artists_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/artists/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New artist</h1>

  <%= render "form", artist: @artist %>

  <%= link_to "Back to artists", artists_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/artists/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @artist %>

    <%= link_to "Edit this artist", edit_artist_path(@artist), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to artists", artists_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this artist", @artist, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>

app/views/artists/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Artist" %>

  <div class="flex justify-between items-center mb-5">
    <h1 class="font-bold text-4xl">Artists</h1>
    <%= link_to "New artist", new_artist_path, class: "rounded-lg py-3 px-5 bg-cyan-500 text-white block font-medium" %>
  </div>

  <table class="min-w-full mt-5">
    <thead>
      <tr>
        <th class="px-4 py-2 bg-cyan-500 text-left">Name</th>
        <th class="px-4 py-2 bg-cyan-500 text-left">Year</th>
        <th class="px-4 py-2 bg-cyan-500 text-left">Nationality</th>
        <th class="px-4 py-2 bg-cyan-500 text-left">Biography</th>
      </tr>
    </thead>
    <tbody>
      <% @artists.each do |artist| %>
        <tr class="cursor-pointer hover:bg-cyan-500" onclick="window.location='<%= artist_path(artist) %>'">
          <td class="border px-4 py-2"><%= artist.name %></td>
          <td class="border px-4 py-2"><%= artist.year %></td>
          <td class="border px-4 py-2"><%= artist.nationality %></td>
          <td class="border px-4 py-2"><%= artist.biography %></td>
           
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>