config/routes.rb
Rails.application.routes.draw do
  get 'statics/index'
  devise_for :users, controller: {
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  # Admin namespace
  
  
  authenticated :user, -> user {user.admin?} do
    root to: 'admin/dashboards#index', as: :admin_root_path
  end
  
  authenticated :user do
    root to: 'client/dashboards#index', as: :client_root_path
  end

  # Define the fallback root path for unautenticated
  unauthenticated do
    root to:'statics#index'
  end


  #Admin namespace
  authenticate :user, ->(user) { user.admin?} do
    namespace :admin do

      root "dashboard#index"    #Admin dashboard root
      resources :albums
      resources :songs, param: :id
      resources :artists
    end
  end
    
  #Client namespace
    namespace :client do

      root "dashboard#index"    #Admin dashboard root
      get 'statics/about', to: 'statics#about'
      get 'statics/contact', to: 'statics#contact'
      resources :albums, only: [:index, :show]
      resources :artists, only: [:index, :show]
      resources :statics
      resources :songs, only: [:index, :show]
    end
      
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  get "about" => "statics#about"
  get "contact" => "statics#contact"
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    "admin_"
  end
end

app/models/admin/dashboard.rb
class Admin::Dashboard < ApplicationRecord
end

app/models/album.rb
class Album < ApplicationRecord
    has_one_attached :image

    has_many :album_songs, dependent: :destroy
    has_many :songs, through: :album_songs
    
end

app/models/album_song.rb
class AlbumSong < ApplicationRecord
  belongs_to :album
  belongs_to :song
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_rich_text :biography
    
    has_many :artist_songs, dependent: :destroy
    has_many :songs, through: :artist_songs

    validates :name, presence:true
end

app/models/artist_song.rb
class ArtistSong < ApplicationRecord
  belongs_to :artist
  belongs_to :song
end

app/models/client.rb
module Client
  def self.table_name_prefix
    "client_"
  end
end

app/models/client/dashboard.rb
class Client::Dashboard < ApplicationRecord
end

app/models/playlist.rb
class Playlist < ApplicationRecord
    has_many :playlist_songs
    has_many :songs, through: :playlist_songs
end

app/models/playlist_song.rb
class PlaylistSong < ApplicationRecord
  belongs_to :playlist
  belongs_to :song
end

app/models/song.rb
class Song < ApplicationRecord
    has_one_attached :file
    has_one_attached :image

    extend FriendlyId
    friendly_id :title, use: :slugged

    has_many :artist_songs, dependent: :destroy
    has_many :artist, through: :artist_songs

    has_one :album_song, dependent: :destroy
    has_one :album, through: :album_song

    has_many :playlist_songs
    has_many :playlist, through: :playlist_songs
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
    def index
    end
    def about
    end
    def contact
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/shared/_nav.html.erb
<nav class="w-full flex justify-between mx-auto my-3 fixed top-0 item-center py-2 px-4 rounded-none border-black border-x-b bg-blue-400">
<span class="grid h-10 w-32 place-content-center rounded-lg bg-gray-100 text-bold text-black-600">
       <%= link_to "Our Music", root_path, class: "" %>
    </span>  
    <div class="flex justify-between">
    <button class="inline-block rounded-md px-4 py-2 text-sm text-white-500 hover:text-gray-700">
        <%= link_to "Artist", client_artists_path, class: "" %>
    </button>
    <button class="inline-block rounded-md px-4 py-2 text-sm text-white-500 hover:text-gray-700">
        <%= link_to "Song", client_songs_path, class: "" %>
    </button>
    <button class="inline-block rounded-md px-4 py-2 text-sm text-white-500 hover:text-gray-700">
        <%= link_to "Album", client_albums_path, class: "" %>
    </button>
    <button class="inline-block rounded-md px-4 py-2 text-sm text-white-500 hover:text-gray-700">
        <%= link_to "About Dashboard", client_statics_about_path, class: "" %>
    </button>
    <button class="inline-block rounded-md px-4 py-2 text-sm text-white-500 hover:text-gray-700">
        <%= link_to "Contact Dashboard", client_statics_contact_path, class: "" %>
    </button>

        
    
        <% if user_signed_in? %>
            
            <button class="inline-block rounded-md px-4 py-2 text-sm text-white-500 hover:text-gray-700">
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "text-white" %>
            </button>
            <button class="inline-block rounded-md px-4 py-2 text-sm text-white-500 hover:text-gray-700">
                <%= link_to "Profile", edit_user_registration_path, class: "text-white" %>
            </button>

        <% else %>
        
            <button class="inline-block rounded-md px-4 py-2 text-sm text-white-500 hover:text-gray-700">
                <%= link_to "Login", new_user_session_path, class: "text-white" %>
            </button>
            <button class="inline-block rounded-md px-4 py-2 text-sm text-white-500 hover:text-gray-700">
                <%= link_to "Sign in", new_user_registration_path, class: "text-white" %>
            </button>
        <% end %>
    </div>
    </div>
</nav>
    